config/routes.rb
require 'sidekiq/web'

Library::Application.routes.draw do
  resources :channels

  root :to => "channels#index"
  get "signup" => "users#new"
  get "channels/:channel_id/topics/new" => "topics#new", as: "submit_topic"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "/auth/twitter/callback", :to => "users#twitter_auth"
  get "/users/:user_id/twitter-info.html" => "users#twitter_info"
 mount Sidekiq::Web, at: "/sidekiq"

  

  resources :votes, only: :create
  resources :users, except: :index
  resources :categories, except: :index
  resources :topics, except: [:index, :new] do
    resources :topic_links, :only => [:new, :create, :edit, :update, :destroy], :path => "links", :as => "links" do
      resources :votes, :only => [:create, :destroy]
    end
  end

end

app/models/channel.rb
# == Schema Information
#
# Table name: channels
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Channel < ActiveRecord::Base
  attr_accessible :title
  has_many :categories, dependent: :destroy
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_filter :load_user
  before_filter :check_if_admin, only: [:new, :create, :edit, :update, :destroy]


  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @channels }
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel = Channel.includes([:categories => [:topics]]).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/new
  # GET /channels/new.json
  def new
    @channel = Channel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/1/edit
  def edit
    @channel = Channel.includes([:categories => [:topics]]).find(params[:id])
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(params[:channel])

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render json: @channel, status: :created, location: @channel }
      else
        format.html { render action: "new" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.json
  def update
    @channel = Channel.includes([:categories => [:topics]]).find(params[:id])

    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel = Channel.includes([:categories => [:topics]]).find(params[:id])
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_category_list.html.erb
<div class="features-four">
  <div class="row">
    <% target.each do |category| %>
      <div class="span5">
        <div class="f-block b-white">
          <h3><%= link_to category.title, category %></h3>
          <p class="links">Number of topics: <%= link_to category.topics.length, category %></p>
        </div>
      </div>
  <% end %>
  </div>
</div>

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/_top_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span>Menu</span>
    </a>
    <div class="nav-collapse collapse">
      <ul class="nav">
        <li class="app_name"><%= link_to 'LIBRARY', root_path %></li>
      </ul>
      <ul class="nav pull-right">
        <% if !logged_in? %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log In", login_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged In as <%= current_user.username %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Profile", user_path(current_user)%></%></%></li>
              <li><%= link_to "Log Out", logout_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<div>
  <div class="welcome">
    <h1>Welcome to Library</h1>
    <p>Find the best resources for any topic.</p>
    <p>Link your twitter account and see what your friends have to say.</p>
    <p>Choose a channel from the navigation bar on the left to get started.</p>
    <%= image_tag("library-picture.jpg", :alt => "Best Resource EVER!", width: '750') %>
  </div>
</div><!--/span-->

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<div>
  <h2><%= @channel.title %></h2>
  <% if has_admin_privileges? %>
    <p><%= link_to 'Edit', edit_channel_path(@channel) %> |
    <%= link_to 'Destroy', @channel, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
  <hr>
<%= render partial: 'channels/category_list', locals: {target: @channel.categories} %>
</div><!--/span-->