config/routes.rb
require 'sidekiq/web'

Library::Application.routes.draw do
  resources :channels

  root :to => "channels#index"
  get "signup" => "users#new"
  get "channels/:channel_id/topics/new" => "topics#new", as: "submit_topic"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "/auth/twitter/callback", :to => "users#twitter_auth"
  get "/users/:user_id/twitter-info.html" => "users#twitter_info"
 mount Sidekiq::Web, at: "/sidekiq"

  

  resources :votes, only: :create
  resources :users, except: :index
  resources :categories, except: :index
  resources :topics, except: [:index, :new] do
    resources :topic_links, :only => [:new, :create, :edit, :update, :destroy], :path => "links", :as => "links" do
      resources :votes, :only => [:create, :destroy]
    end
  end

end

app/models/topic_link.rb
# == Schema Information
#
# Table name: topic_links
#
#  id          :integer          not null, primary key
#  link_id     :integer
#  topic_id    :integer
#  score       :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  title       :string(255)
#  description :text
#  user_id     :integer
#

require 'open-uri'

class TopicLink < ActiveRecord::Base
  attr_accessible :link_id, :score, :topic_id, :title, :description, :link_attributes, :user_id

  belongs_to :topic
  belongs_to :link
  accepts_nested_attributes_for :link

  belongs_to :user #owner

  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, class_name: 'User', foreign_key: 'topic_link_id', source: :user

  validates_presence_of :title

  default_scope order('topic_links.score DESC, topic_links.updated_at DESC')

  def authorize?(user)
    user && (user.admin? || (self.user_id==user.id && is_score_zero?))
  end

  def is_score_zero?
    self.score == 0
  end

  def update_score(vote)
    self.score += vote
    self.save
  end

  def has_no_prior_vote?(prior_vote)
    prior_vote.nil?
  end

  def cast_vote(prior_vote_instance, submit_params, submit_status)
    self.update_score(submit_status)
    if self.has_no_prior_vote?(prior_vote_instance)
      self.votes.build(submit_params).save
    else
      prior_vote_instance.update_vote(submit_status)
    end
  end

  def scrape(url)
    web_address = open(url, :ssl_verify_mode => OpenSSL::SSL::VERIFY_NONE)
    page = Nokogiri::HTML(web_address)
    self.title = page.css("title").text
  end

  def create_associate_or_reject_link
    existing_link = Link.find_by_url(self.link.url)
    if existing_link && self.topic.includes_link?(existing_link) #link exists and already belongs to this topic
      false #don't save it
    else
      self.link = existing_link if existing_link #link exists but does not belong to this topic
      self.save #link is completely new, just save it
    end
  end

  def friend_up_voters(current_user)
    @friends ||= current_user.collect_friend_ids
    @friend_up_voters ||= self.votes.includes(:user).where(status: 1, user_id: @friends)
  end

  def friends_score(current_user)
    self.friend_up_voters(current_user).size
  end

end

app/controllers/topic_links_controller.rb
class TopicLinksController < ApplicationController
  before_filter :load_user
  before_filter :check_if_logged_in
  before_filter :load_topic_link, :only => [:update, :destroy, :edit]
  before_filter :tl_admin_or_creator, :only => [:update, :destroy, :edit]

  
  # GET /topic_links/new
  # GET /topic_links/new.json
  def new
    @topic_link = TopicLink.new
    @topic = Topic.find(params[:topic_id])
    @link = Link.new
    render template: 'modals/topic-link-submit', layout:false
  end

 # when editing a topic link, want to check if edited topic_link already exists.  if it already
 # exists, then we want to make the edited link_link_id = to the existing topic_link_link_id

  # GET /topic_links/1/edit
  def edit
    @topic_link = TopicLink.find(params[:id])
    @topic=@topic_link.topic
    @category = @topic_link.topic.category
    @link = @topic_link.link
    render template: 'modals/topic-link-edit', layout:false
  end

  # POST /topic_links
  # POST /topic_links.json
  def create
    @link = Link.new(url: params[:link][:url].strip.downcase)
    @link.prepend_http
    @topic = Topic.includes(:category => :channel).find(params[:topic_id])  
    @topic_link = TopicLink.new(params[:topic_link])
    @topic_link.topic = @topic
    @topic_link.user = current_user

    if @link.is_valid? 
      @topic_link.link = @link
      @topic_link.create_associate_or_reject_link
      redirect_to @topic
    else 
      redirect_to @topic
      flash[:error] = "Invalid URL"
      
    end
  end

  # PUT /topic_links/1
  # PUT /topic_links/1.json
  def update
    @submitted_link = Link.new(url: params[:link][:url].strip.downcase)
    @submitted_link.prepend_http
    @topic = Topic.find(params[:topic_id])
    @topic_link = TopicLink.find(params[:id])
    @topic_link.update_attributes(params[:topic_link])
    @link = @topic_link.link

    if @submitted_link.is_valid? 
      @topic_link.link = @submitted_link
      @topic_link.create_associate_or_reject_link
      if @link.topic_links.length <1
        @link.destroy
      end
      redirect_to @topic
    else 
      flash[:error] = "Invalid URL"
      @request_url = {url: topic_link_path(@topic.id, @topic_link)}
      render 'topic_links/edit'
    end
  end

  # DELETE /topic_links/1
  # DELETE /topic_links/1.json
  def destroy
    @topic_link = TopicLink.find_by_id(params[:id])
    @link = Link.find_by_id(@topic_link.link_id)
    @topic = @topic_link.topic
    @topic_link.destroy
    @link.destroy if TopicLink.where(link_id: @topic_link.link_id).length == 0

    respond_to do |format|
      format.html { redirect_to @topic }
      format.json { head :no_content }
    end
  end

  private

    def load_topic_link
      @topic_link = TopicLink.find(params[:id])
    end
    def tl_admin_or_creator
      redirect_to root_path, notice: "You are not authorized to do that!" if (! @topic_link.authorize?(current_user))
    end
end

app/helpers/topic_links_helper.rb
module TopicLinksHelper
end

app/views/topic_links/_form.erb
<a href="#myModal" role="button" class="btn" data-toggle="modal">Add a New Link</a>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <% if logged_in? %>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Submit a Link</h3>
    </div>
    <div class="modal-body">
        <%= form_for(@topic_link, :url => topic_links_path(@topic)) do |f| %>
        <%= render "shared_partials/error_messages", :target => @topic_link %>
    <div class="field">
        <%= fields_for @link do |l|%>
            <%= l.label "Url:" %>
            <%= l.text_field :url, value: 'http://' %>
        <% end %>
        <%= f.label "Title:" %>
        <%= f.text_field :title %><br>
        <%= f.label "Description:" %>
        <%= f.text_area :description, :rows=> 4 %><br/>
        <%= f.submit "Submit" %>
    </div>
    </div>
        <% end %>
    <% else %>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Please Log In</h3>
    </div>
    <div class="modal-body">
        <%= render 'sessions/form' %>
    </div>
    <% end %>
</div>

app/views/topic_links/_form.html.erb
<%= form_for(@topic_link, url: path) do |f| %>
    <%= render "shared_partials/error_messages", :target => @topic_link %>
    <div class="field">
        <%= fields_for @link do |l|%>
        <%= l.label "Url:" %>
        <%= l.text_field :url %>
        <% end %>
    <%= f.label "Title:" %>
    <%= f.text_field :title %><br>
    <%= f.label "Description:" %>
    <%= f.text_area :description, :rows=> 4 %><br/>
    <%= f.submit "Submit" %>
    </div>

<% end %>

app/views/topic_links/_form_modal.html.erb
<div id="tlFormModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Submit a Link</h3>
    </div>
    <div class="modal-body">
        <%= render partial:'topic_links/form'%>
    </div>
</div>

app/views/topic_links/_link_list.html.erb
<tr class="link_item">
  <td class="link_score task <%= "best_link" if tl == @topic.best_link %> ">
    <%= form_tag(topic_link_votes_path(topic_id:@topic.id, link_id:tl.id )) do%>
      <%= hidden_field(:vote, :status, value: 1) %>
      <%= hidden_field(:vote, :user_id, value: session[:user_id]) %>
      <% if logged_in? %>
        <%= image_submit_tag "upvote.png"%>
      <% else %>
        <a href="#loginModal" role="button" class="btn vote login-link" data-toggle="modal"><%=image_tag "upvote.png"%></a>
      <% end %>
    <% end %>

    <%= tl.score %>

    <%= form_tag(topic_link_votes_path(topic_id:@topic.id, link_id:tl.id )) do %>
      <%= hidden_field(:vote, :status, value: -1) %>
      <%= hidden_field(:vote, :user_id, value: session[:user_id]) %>
      <% if logged_in? %>
        <%= image_submit_tag "downvote.png"%>
      <% else %>
        <a href="#" role="button" class="btn vote login-link" data-toggle="modal"><%=image_tag "downvote.png"%></a>
      <% end %>
    <% end%>
  </td>
  <td class="link_info task <%= "best_link" if tl == @topic.best_link %> ">
    <h6><%= link_to tl.title, tl.link.url, title: tl.link.url, rel: 'tooltip' %></h6>
    <p><%= tl.description %></p>
    <div class="tmeta"><i class="icon-calendar"></i> <%= time_ago_in_words(tl.created_at) %> ago | <i class="icon-user"></i> Submitted by <%= link_to tl.user.username, user_path(tl.user_id) %></div>
    <% if current_user && tl.friend_up_voters(current_user).length > 0 %>
      Voted up by <%= tl.friends_score(current_user) %>
      <% if tl.friend_up_voters(current_user).length > 1 %>
        people you follow:
      <% else %>
        person you follow:
      <% end %>
      <%tl.friend_up_voters(current_user).each do |f| %>
        <%= link_to User.find(f.user_id).username, user_path(f.user_id) %><%= "," if f != tl.friend_up_voters(current_user).last %>
      <% end %>
    <% end %>
    <% if tl.authorize?(current_user) %>
      <p><a hred="#" data-topic-link="<%=tl.id%>" class="topic-link-edit-link">Edit</a> |
      <%= link_to "Delete", topic_link_path(@topic, tl), method: :delete, data: { confirm: 'Are you sure?' }%></p>
    <% end %>
  </td>
</tr>

app/views/topic_links/edit.html.erb
<h1>Editing topic link</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic_link.topic %> |
<%= link_to 'Back', topic_path(@topic_link.topic) %>