config/routes.rb
require 'sidekiq/web'

Library::Application.routes.draw do
  resources :channels

  root :to => "channels#index"
  get "signup" => "users#new"
  get "channels/:channel_id/topics/new" => "topics#new", as: "submit_topic"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "/auth/twitter/callback", :to => "users#twitter_auth"
  get "/users/:user_id/twitter-info.html" => "users#twitter_info"
 mount Sidekiq::Web, at: "/sidekiq"

  

  resources :votes, only: :create
  resources :users, except: :index
  resources :categories, except: :index
  resources :topics, except: [:index, :new] do
    resources :topic_links, :only => [:new, :create, :edit, :update, :destroy], :path => "links", :as => "links" do
      resources :votes, :only => [:create, :destroy]
    end
  end

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  channel_id :integer
#

class Category < ActiveRecord::Base
  attr_accessible :title, :channel_id
  has_many :topics, :dependent => :destroy
  belongs_to :channel
  validates_presence_of :title

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :load_user
  before_filter :check_if_admin, only: [:create, :edit, :update, :destroy, :new]

  # GET /categories
  # GET /categories.json
  # def index
  #   per_page = params[:per_page] || 5
  #   @categories = Category.page(params[:page]).per_page(per_page.to_i)

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @categories }
  #   end
  # end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.includes(:channel=>[:categories=>[:topics]], :topics => [:topic_links, :best_link => [:link]]).order("topics.title ASC").find_by_id(params[:id])
    @channel = @category.channel
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.includes(:channel=>[:categories=>[:topics]], :topics => [:topic_links]).order("topics.title ASC").find_by_id(params[:id])
    @channel = @category.channel
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.includes(:channel=>[:categories=>[:topics]], :topics => [:topic_links]).order("topics.title ASC").find_by_id(params[:id])
    @channel = @category.channel

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.includes(:channel=>[:categories=>[:topics]], :topics => [:topic_links]).order("topics.title ASC").find_by_id(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to @category.channel }
      format.json { head :no_content }
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <%= render "shared_partials/error_messages", :target => @category %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
    <%= f.label :channel %>
    <%= f.collection_select(:channel_id, Channel.all, :id, :title) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_left_navbar_content.html.erb
<li class="nav-header">Categories</li><hr>
  <div class="dropdown">
    <ul class="nav nav-list">
      <% @channel.categories.order("title ASC").each do |c| %>
        <li class="dropdown-submenu"><%= link_to c.title, category_path(c) %>
          <ul class="dropdown-menu">
            <% c.topics.order("title ASC").each do |t| %>
              <li><%= link_to t.title, topic_path(t) %></li>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</li>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div>
  <h2><%= link_to @channel.title, @channel %> > <%= @category.title %></h2>
  <% if has_admin_privileges? %>
      <p><%= link_to 'Edit', edit_category_path(@category) %> |
      <%= link_to 'Destroy', @category, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
  <hr>
  <%= render partial: 'shared_partials/topic_list', locals: {target: @category.topics}%>
</div>