config/routes.rb
require 'sidekiq/web'

Library::Application.routes.draw do
  resources :channels

  root :to => "channels#index"
  get "signup" => "users#new"
  get "channels/:channel_id/topics/new" => "topics#new", as: "submit_topic"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy"
  get "/auth/twitter/callback", :to => "users#twitter_auth"
  get "/users/:user_id/twitter-info.html" => "users#twitter_info"
 mount Sidekiq::Web, at: "/sidekiq"

  

  resources :votes, only: :create
  resources :users, except: :index
  resources :categories, except: :index
  resources :topics, except: [:index, :new] do
    resources :topic_links, :only => [:new, :create, :edit, :update, :destroy], :path => "links", :as => "links" do
      resources :votes, :only => [:create, :destroy]
    end
  end

end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">

      <div class="widgets">
        <div class="span4">
          <div class="fwidget">

            <div class="col-l">
              <h6>Downlaods</h6>
              <ul>
                <li><a href="#">Condimentum</a></li>
                <li><a href="#">Etiam at</a></li>
                <li><a href="#">Fusce vel</a></li>
                <li><a href="#">Vivamus</a></li>
                <li><a href="#">Pellentesque</a></li>
              </ul>
            </div>

            <div class="col-r">
              <h6>Support</h6>
              <ul>
                <li><a href="#">Condimentum</a></li>
                <li><a href="#">Etiam at</a></li>
                <li><a href="#">Fusce vel</a></li>
                <li><a href="#">Vivamus</a></li>
                <li><a href="#">Pellentesque</a></li>
              </ul>
            </div>

          </div>
        </div>

        <div class="span4">
          <div class="fwidget">
            <h6>Categories</h6>
            <ul>
              <li><a href="#">Condimentum - Condimentum gravida</a></li>
              <li><a href="#">Etiam at - Condimentum gravida</a></li>
              <li><a href="#">Fusce vel - Condimentum gravida</a></li>
              <li><a href="#">Vivamus - Condimentum gravida</a></li>
              <li><a href="#">Pellentesque - Condimentum gravida</a></li>
            </ul>
          </div>
        </div>

        <div class="span4">
          <div class="fwidget">
            <h6>Recent Posts</h6>
            <ul>
              <li><a href="#">Sed eu leo orci, condimentum gravida metus</a></li>
              <li><a href="#">Etiam at nulla ipsum, in rhoncus purus</a></li>
              <li><a href="#">Fusce vel magna faucibus felis dapibus facilisis</a></li>
              <li><a href="#">Vivamus scelerisque dui in massa</a></li>
              <li><a href="#">Pellentesque eget adipiscing dui semper</a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="span12">
          <div class="copy">
            <h6>Motro <span class="color">Mania</span></h6>
            <p>Copyright &copy; <a href="#">Your Site</a> - <a href="index.html">Home</a> | <a href="aboutus.html">About Us</a> | <a href="faq.html">FAQ</a> | <a href="contactus.html">Contact Us</a></p>
          </div>
      </div>
    </div>
  <div class="clearfix"></div>
  </div>
</footer> 

app/views/layouts/_left_categories.html.erb
<li><p class="nav-header">Categories in <%= @channel.title %> </p>
  <div class="dropdown">
    <ul class="nav nav-list">
      <%= render partial: 'layouts/left_categories_list', collection: categories, as: :c %>
    </ul>
  </div>
</li>

app/views/layouts/_left_categories_list.html.erb
<li class="dropdown-submenu"><%= link_to c.title, category_path(c) %>
  <ul class="dropdown-menu">
    <% c.topics.each do |t| %>
      <li><%= link_to t.title, t %></li>
    <% end %>
  </ul>
</li>

app/views/layouts/_left_channel_list.html.erb
<li><%= link_to c.title, channel_path(c) %></li>

app/views/layouts/_left_channels.html.erb
<li><p class="nav-header">Select a Channel</p>
  <ul class = "nav nav-list">
    <%= render partial: 'layouts/left_unnested_list', collection: Channel.order("title ASC").all, as: :c %>
  </ul>
</li>

app/views/layouts/_left_topics.html.erb
<li><p class="nav-header">Topics <br> in <br> <%= @category.title %> </p>
  <ul class = "nav nav-list">
    <%= render partial: 'layouts/left_unnested_list', collection: @category.topics, as: :c %>
  </ul>
</li>
<hr>

app/views/layouts/_left_unnested_list.html.erb
<li><%= link_to c.title, c %></li>

app/views/layouts/_menubar.html.erb
<!-- Navigation bar starts -->
<div class="navbar">
  <div class="navbar-inner">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span>Menu</span>
    </a>
    <div class="nav-collapse collapse">
      <ul class="nav">
        <li class="app_name dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">LIBRARY<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Home", root_path %></li>
            <% Channel.order("title ASC").all.each do |c| %>
              <li><%= link_to c.title, channel_path(c) %></li>
            <% end %>
          </ul>
        </li>
        <% if @channel %>
          <li><a href="#" data-channel="<%=@channel.id%>" class="<%= ("login-link" if !logged_in?) || "topic-submit-link" %>">Submit A Topic</a></li>
        <% end %>
      </ul>
      <ul class="nav pull-right">
        <% if !logged_in? %>
          <li><a href="#" class="login-link">Log In</a></li>
          <li><a href="#" class="signup-link">Sign Up</a></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged In as <%= current_user.username %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Profile", user_path(current_user)%></li>
              <li><%= link_to "Account Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Log Out", logout_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_search.html.erb
<%= form_tag category_path, method: :put do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", name: nil %>
  <p>
<% end %>

app/views/layouts/_sidebar.html.erb
<div>
  <div class="well sidebar-nav">
  <ul class="nav nav-list">
    <%= render partial: 'layouts/left_topics' if @category %>
    <%= render partial: 'layouts/left_channels' unless @channel %>
    <%= (render partial: 'layouts/left_categories', locals: {categories: @channel.categories}) if @channel %>
  </ul>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Library</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%#= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <!-- HTML5 Support for IE -->
    <!--[if lt IE 9]>
    <script src="js/html5shim.js"></script>
    <![endif]-->
  </head>

  <body>
    <div id="modal-wrapper"></div>
    <%# render partial: 'shared_partials/login_modal' unless logged_in? %>
    <%# render partial: 'shared_partials/signup_modal' unless logged_in? %>
    <%# render partial: 'topics/form_modal', locals: {topic: Topic.new} if ( @channel && logged_in?)%>
    <%= render partial: 'layouts/menubar' %>

    <div class="content">
      <div class="container-fluid">
      <div class = "row-fluid table-wrap">
        <div class="sidebar2">

          <%= render partial: 'layouts/sidebar' %> 
        </div>
          

        <div class="main">
      <div class="main-content">
          <%= render partial: 'shared_partials/flash_messages' %>
          <%= yield %>
        </div>
        </div>
      </div>
    </div>
  </div>

  </body>
</html>